name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          lein: 'latest'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run tests"
        run: lein test

  build-native-image-linux:
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v4.0.2
        id: semver
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}"
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: true

      - run: git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline > new-in-this-release.log

      - name: Read git log
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./new-in-this-release.log

      - name: "Create Release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.semver.outputs.version_tag}}
          release_name: ${{steps.semver.outputs.version_tag}}
          body: ${{ steps.package.outputs.content }}
          draft: false
          prerelease: false

      - name: Build a uberjar
        run: lein uberjar

      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.0.0.2'
          java: 'java17'
          arch: 'amd64'

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image

      - name: Build a native image
        run: lein native

      - name: "Publish"
        uses: actions/upload-artifact@v2-preview
        with:
          name: bruno-linux
          path: bruno

      - name: "Upload"
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: bruno
          asset_name: bruno-linux
          asset_content_type: application/octet-stream